var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';
OA_output['Sidebar 1'] += "<"+"!--<"+"span class=\"declare\">Advertisement<"+"/span>-->\n";
OA_output['Sidebar 1'] += "<"+"div style=\"height:20px;\"><"+"/div><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7986__zoneid=40__OXLCA=1__cb=848f4fe510__oadest=https%3A%2F%2Fwww.lightcms.com%2Fpartners%3Futm_source%3DCommindo%26utm_medium%3Dbanner%26utm_campaign%3DCommindo_PP_Tour%26leadsource%3Dlcms_pp_tour_commindo\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=2014-ad-worldsbest-green190x400_mini_3.jpg&contenttype=jpeg\' width=\'190\' height=\'400\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_848f4fe510\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7986&amp;campaignid=2923&amp;zoneid=40&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=848f4fe510\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar 2'] = '';

OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8007__zoneid=22__OXLCA=1__cb=4b26cc26f2__oadest=https%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Content%29%26utm_medium%3Dbanner%26utm_content%3DLovedByDesigners%26utm_campaign%3DSmashing%26leadsource%3Dlcms_commindo_design\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=2014-ad-worldsbest-green300x250_mini_5.jpg&contenttype=jpeg\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_4b26cc26f2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8007&amp;campaignid=2926&amp;zoneid=22&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=4b26cc26f2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Homepage prem Ad'] = '';
OA_output['Homepage prem Ad'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7996__zoneid=25__OXLCA=1__cb=7c664380d8__oadest=https%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Homepage%252BPremium%29%26utm_medium%3Dbanner%26utm_content%3DLovedByDesigners%26utm_campaign%3DSmashing%26leadsource%3Dlcms_commindo_design\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=2014-ad-hasslefree-blue540x150_mini_5.jpg&contenttype=jpeg\' width=\'540\' height=\'150\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_7c664380d8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7996&amp;campaignid=2924&amp;zoneid=25&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=7c664380d8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar Special 1'] = '';
OA_output['Sidebar Special 1'] += "<"+"div class=\"sidebar_special_banner\">\n";
OA_output['Sidebar Special 1'] += "<"+"!-- test --><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7981__zoneid=72__OXLCA=1__cb=75fa0308ec__oadest=https%3A%2F%2Fwww.lightcms.com%2Fpartners%3Futm_source%3DCommindo%26utm_medium%3Dbanner%26utm_campaign%3DCommindo_PP_Tour%26leadsource%3Dlcms_pp_tour_commindo\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=2014-ad-hasslefree-green420x200_mini_3.jpg&contenttype=jpeg\' width=\'420\' height=\'200\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_75fa0308ec\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7981&amp;campaignid=2922&amp;zoneid=72&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=75fa0308ec\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Sidebar Special 2'] = '';
OA_output['Sidebar Special 2'] += "<"+"div class=\"sidebar_special_banner\">\n";
OA_output['Sidebar Special 2'] += "<"+"!-- test --><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7950__zoneid=72__OXLCA=1__cb=f5c0d6b80e__oadest=https%3A%2F%2Fdeveloper.amazon.com%2Fappsandservices%2F%3Fsc_channel%3DBA%26sc_brand%3DFire_phone%26sc_campaign%3DFire_phone_Acq%26sc_place%3D420x200%26sc_country%3DUS%26sc_detail%3DBA_ATS%26sc_segment%3DGameDevelopers%26sc_publisher%3DSmashingMagazine%26sc_medium%3DBA_Fire_phone_Fire_phone_Acq_420x200_BA_ATS_GameDevelopers_SmashingMagazine_US\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_420x200_ats.jpg&contenttype=jpeg\' width=\'420\' height=\'200\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_f5c0d6b80e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7950&amp;campaignid=2914&amp;zoneid=72&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=f5c0d6b80e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\"><"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OA_output['Textad'] += "document.MAX_ct0 =\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=ed6db2f644__oadest=\';\n";
OA_output['Textad'] += "var m3_u = (location.protocol==\'https:\'?\'https://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\':\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\');\n";
OA_output['Textad'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['Textad'] += "if (!document.MAX_used) document.MAX_used = \',\';\n";
OA_output['Textad'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['Textad'] += "document.write (\"?zoneid=94\");\n";
OA_output['Textad'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['Textad'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['Textad'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['Textad'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['Textad'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['Textad'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['Textad'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['Textad'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['Textad'] += "}\n";
OA_output['Textad'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['Textad'] += "document.write (\"\'><"+"\\/scr\"+\"ipt>\");\n";
OA_output['Textad'] += "//]]>--><"+"/script><"+"noscript><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=ed6db2f644__oadest=http%3A%2F%2Fauslieferung.commindo-media-ressourcen.de%2Fwww%2Fdelivery%2Fck.php%3Fn%3Daf102b35%26amp%3Bcb%3Ded6db2f644\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/avw.php?zoneid=94&amp;cb=ed6db2f644&amp;n=af102b35&amp;ct0=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=ed6db2f644__oadest=\' border=\'0\' alt=\'\' /><"+"/a><"+"/noscript><"+"div id=\'beacon_ed6db2f644\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6259&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=ed6db2f644\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Comment Sponsor'] = '';
OA_output['Comment Sponsor'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8019__zoneid=26__OXLCA=1__cb=19a495c021__oadest=https%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Comment%29%26utm_medium%3Dbanner%26utm_content%3DHTML-Green%26utm_campaign%3DSmashing%26leadsource%3Dlcms_commindo_design\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=html-green-468x90_31.png&contenttype=png\' width=\'468\' height=\'90\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_19a495c021\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8019&amp;campaignid=2928&amp;zoneid=26&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=19a495c021\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';

OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6928__zoneid=24__OXLCA=1__cb=75a01dfdb1__oadest=https%3A%2F%2Fw3-markup.com%2Forder%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_198.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'PSD to HTML Services\' title=\'PSD to HTML Services\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6928__zoneid=24__OXLCA=1__cb=75a01dfdb1__oadest=https%3A%2F%2Fw3-markup.com%2Forder%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew\' target=\'_blank\'>PSD to HTML Services<"+"/a><"+"div id=\'beacon_75a01dfdb1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6928&amp;campaignid=2394&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=75a01dfdb1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7970__zoneid=24__OXLCA=1__cb=31c2fa0380__oadest=https%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DLovedByDesigners%26utm_campaign%3DSmashing%26leadsource%3Dlcms_commindo_design\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_184.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Sign Up for Free!\' title=\'Sign Up for Free!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7970__zoneid=24__OXLCA=1__cb=31c2fa0380__oadest=https%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DLovedByDesigners%26utm_campaign%3DSmashing%26leadsource%3Dlcms_commindo_design\' target=\'_blank\'>Sign Up for Free!<"+"/a><"+"div id=\'beacon_31c2fa0380\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7970&amp;campaignid=2921&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=31c2fa0380\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"style type=\"text/css\">\n";
OA_output['spnsr ROS 3'] += ".bnnr-list .GoogleActiveViewClass { display: inline; }\n";
OA_output['spnsr ROS 3'] += "<"+"/style>\n";
OA_output['spnsr ROS 3'] += "<"+"SCRIPT LANGUAGE=\"JavaScript\">\n";
OA_output['spnsr ROS 3'] += "ord=Math.random();\n";
OA_output['spnsr ROS 3'] += "ord=ord*10000000000000000000;\n";
OA_output['spnsr ROS 3'] += "document.write(\'<"+"SCR\' + \'IPT LANGUAGE=\"JavaScript\" SRC=\"http://ad.doubleclick.net/adj/N6807.287930.SMASHINGMAGAZINE.C1/B8037284.2;click0=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7162__zoneid=24__OXLCA=1__cb=3887b8b700__oadest=;sz=200x125;click=;ord=\'+ord+\'?\"><"+"\\/SCR\' + \'IPT>\');\n";
OA_output['spnsr ROS 3'] += "<"+"/SCRIPT>\n";
OA_output['spnsr ROS 3'] += "<"+"NOSCRIPT>\n";
OA_output['spnsr ROS 3'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7162__zoneid=24__OXLCA=1__cb=3887b8b700__oadest=http%3A%2F%2Fad.doubleclick.net%2Fjump%2FN6807.287930.SMASHINGMAGAZINE.C1%2FB8037284.2%3Bsz%3D200x125%3Bord%3D123456789%3F\" target=\"_blank\">\n";
OA_output['spnsr ROS 3'] += "<"+"IMG SRC=\"http://ad.doubleclick.net/ad/N6807.287930.SMASHINGMAGAZINE.C1/B8037284.2;sz=200x125;ord=123456789?\" WIDTH=\"200\" HEIGHT=\"125\" BORDER=\"0\" ALT=\"Click here...\"><"+"/A>\n";
OA_output['spnsr ROS 3'] += "<"+"/NOSCRIPT><"+"br>\n";
OA_output['spnsr ROS 3'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7162__zoneid=24__OXLCA=1__cb=3887b8b700__oadest=http%3A%2F%2Fad.doubleclick.net%2Fjump%2FN6807.287930.SMASHINGMAGAZINE.C1%2FB8037284.2%3Bsz%3D200x125%3Bord%3D123456789%3F\" target=\"_blank\">$1 an Image. Always.<"+"/A><"+"div id=\'beacon_3887b8b700\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7162&amp;campaignid=2669&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=3887b8b700\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8227__zoneid=24__OXLCA=1__cb=e08c15d41a__oadest=https%3A%2F%2Fworkingatbooking.com%2Fvacancies%2F%3Ffilter-searchphrase%3Ddesign%26filter-company%3Dtechnology%26filter-city%3Damsterdam%26utm_source%3DSmashingmagazine%26utm_medium%3Dbanner%26utm_campaign%3DMF_Banners%23heading\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sponsor_ad-1.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Designer jobs at Booking.com\' title=\'Designer jobs at Booking.com\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8227__zoneid=24__OXLCA=1__cb=e08c15d41a__oadest=https%3A%2F%2Fworkingatbooking.com%2Fvacancies%2F%3Ffilter-searchphrase%3Ddesign%26filter-company%3Dtechnology%26filter-city%3Damsterdam%26utm_source%3DSmashingmagazine%26utm_medium%3Dbanner%26utm_campaign%3DMF_Banners%23heading\' target=\'_blank\'>Designer jobs at Booking.com<"+"/a><"+"div id=\'beacon_e08c15d41a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8227&amp;campaignid=3015&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=e08c15d41a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8116__zoneid=24__OXLCA=1__cb=6f3c449eec__oadest=http%3A%2F%2Fwww.theconference.se%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=250x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Join The Conference!\' title=\'Join The Conference!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8116__zoneid=24__OXLCA=1__cb=6f3c449eec__oadest=http%3A%2F%2Fwww.theconference.se%2F\' target=\'_blank\'>Join The Conference!<"+"/a><"+"div id=\'beacon_6f3c449eec\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8116&amp;campaignid=2960&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=6f3c449eec\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7487__zoneid=24__OXLCA=1__cb=54385781cc__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DThink%2520Forward%26utm_campaign%3DKent%25202014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=kent_250x125_banner3_uxd_thinkforward.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Kent State Online\' title=\'Kent State Online\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7487__zoneid=24__OXLCA=1__cb=54385781cc__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DThink%2520Forward%26utm_campaign%3DKent%25202014\' target=\'_blank\'>Kent State Online<"+"/a><"+"div id=\'beacon_54385781cc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7487&amp;campaignid=2807&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=54385781cc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7967__zoneid=24__OXLCA=1__cb=8c9e6f7956__oadest=http%3A%2F%2Fbit.ly%2FV9gCre\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=focal-press-color.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Leading Web Design Books​\' title=\'Leading Web Design Books​\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7967__zoneid=24__OXLCA=1__cb=8c9e6f7956__oadest=http%3A%2F%2Fbit.ly%2FV9gCre\' target=\'_blank\'>Leading Web Design Books​<"+"/a><"+"div id=\'beacon_8c9e6f7956\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7967&amp;campaignid=2738&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=8c9e6f7956\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8085__zoneid=24__OXLCA=1__cb=5fbcdd817c__oadest=http%3A%2F%2Fwww.invisionapp.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=invision.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Get Started -- Free Forever\' title=\'Get Started -- Free Forever\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8085__zoneid=24__OXLCA=1__cb=5fbcdd817c__oadest=http%3A%2F%2Fwww.invisionapp.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3Dsmashing\' target=\'_blank\'>Get Started -- Free Forever<"+"/a><"+"div id=\'beacon_5fbcdd817c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8085&amp;campaignid=2942&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=5fbcdd817c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8175__zoneid=24__OXLCA=1__cb=5c28f152df__oadest=http%3A%2F%2Fwww.syncfusion.com%2Fresources%2Ftechportal%2Febooks%3Futm_medium%3DsmashingmagJulAug14\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_15.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Find your inspiration\' title=\'Find your inspiration\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8175__zoneid=24__OXLCA=1__cb=5c28f152df__oadest=http%3A%2F%2Fwww.syncfusion.com%2Fresources%2Ftechportal%2Febooks%3Futm_medium%3DsmashingmagJulAug14\' target=\'_blank\'>Find your inspiration<"+"/a><"+"div id=\'beacon_5c28f152df\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8175&amp;campaignid=2991&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=5c28f152df\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8080__zoneid=24__OXLCA=1__cb=8750901865__oadest=https%3A%2F%2Fgoroost.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=roost_for_smashing_web_2.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Free Trial. Start Now.\' title=\'Free Trial. Start Now.\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8080__zoneid=24__OXLCA=1__cb=8750901865__oadest=https%3A%2F%2Fgoroost.com%2F\' target=\'_blank\'>Free Trial. Start Now.<"+"/a><"+"div id=\'beacon_8750901865\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8080&amp;campaignid=2940&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=8750901865\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8075__zoneid=24__OXLCA=1__cb=681a344400__oadest=https%3A%2F%2Fwww.yootheme.com%2Fwordpress-1%3Futm_source%3DSmashing%26utm_medium%3DBanner%26utm_content%3DSidebar%2520Sponsor%2520Ad%26utm_campaign%3DSmashing%2520Blue%2520Summer\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=yootheme_sponsorad.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'YOOtheme Themes\' title=\'YOOtheme Themes\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8075__zoneid=24__OXLCA=1__cb=681a344400__oadest=https%3A%2F%2Fwww.yootheme.com%2Fwordpress-1%3Futm_source%3DSmashing%26utm_medium%3DBanner%26utm_content%3DSidebar%2520Sponsor%2520Ad%26utm_campaign%3DSmashing%2520Blue%2520Summer\' target=\'_blank\'>YOOtheme Themes<"+"/a><"+"div id=\'beacon_681a344400\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8075&amp;campaignid=2936&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=681a344400\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7494__zoneid=24__OXLCA=1__cb=df9dec1ae1__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=xtheme.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'30+ Demos - See It Live!\' title=\'30+ Demos - See It Live!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7494__zoneid=24__OXLCA=1__cb=df9dec1ae1__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'>30+ Demos - See It Live!<"+"/a><"+"div id=\'beacon_df9dec1ae1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7494&amp;campaignid=2813&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=df9dec1ae1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8159__zoneid=24__OXLCA=1__cb=36fbf2e088__oadest=http%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%3FSM%3D2\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=free-vector-graphics_4.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Free + Royalty Free Vector Art\' title=\'Free + Royalty Free Vector Art\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8159__zoneid=24__OXLCA=1__cb=36fbf2e088__oadest=http%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%3FSM%3D2\' target=\'_blank\'>Free + Royalty Free Vector Art<"+"/a><"+"div id=\'beacon_36fbf2e088\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8159&amp;campaignid=2981&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=36fbf2e088\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8202__zoneid=24__OXLCA=1__cb=7c62b891fa__oadest=http%3A%2F%2Fbugherd.com%2F%3Futm_source%3DSmashingMag%26utm_medium%3DBanner%26utm_content%3D200x125_Simple%26utm_campaign%3DAug2014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smashing-ad-200x125b.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'BugHerd - Simple Bug Tracker\' title=\'BugHerd - Simple Bug Tracker\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8202__zoneid=24__OXLCA=1__cb=7c62b891fa__oadest=http%3A%2F%2Fbugherd.com%2F%3Futm_source%3DSmashingMag%26utm_medium%3DBanner%26utm_content%3D200x125_Simple%26utm_campaign%3DAug2014\' target=\'_blank\'>BugHerd - Simple Bug Tracker<"+"/a><"+"div id=\'beacon_7c62b891fa\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8202&amp;campaignid=3002&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=7c62b891fa\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';
OA_output['spnsr ROS 15'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7964__zoneid=24__OXLCA=1__cb=498928cb26__oadest=http%3A%2F%2Fwww.shopify.com%2Ftour%2Ffor-designers%3Futm_source%3Dsmag%26utm_medium%3Dsmag%26utm_campaign%3Ddesigners\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_182.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Shopify - ecommerce done right\' title=\'Shopify - ecommerce done right\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7964__zoneid=24__OXLCA=1__cb=498928cb26__oadest=http%3A%2F%2Fwww.shopify.com%2Ftour%2Ffor-designers%3Futm_source%3Dsmag%26utm_medium%3Dsmag%26utm_campaign%3Ddesigners\' target=\'_blank\'>Shopify - ecommerce done right<"+"/a><"+"div id=\'beacon_498928cb26\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7964&amp;campaignid=2918&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=498928cb26\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 16'] = '';
OA_output['spnsr ROS 16'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8144__zoneid=24__OXLCA=1__cb=e076a91771__oadest=http%3A%2F%2Fwww.myfonts.com%2Ftopwebfonts%2F%3Futm_source%3DSmashing%26utm_medium%3Dnewuser%26utm_campaign%3D20140715%26reftag%3Dsmashing-webfonts-20140715\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smashing_1.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Easy &amp; flexible with no monthly fees\' title=\'Easy &amp; flexible with no monthly fees\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8144__zoneid=24__OXLCA=1__cb=e076a91771__oadest=http%3A%2F%2Fwww.myfonts.com%2Ftopwebfonts%2F%3Futm_source%3DSmashing%26utm_medium%3Dnewuser%26utm_campaign%3D20140715%26reftag%3Dsmashing-webfonts-20140715\' target=\'_blank\'>Easy &amp; Flexible<"+"/a><"+"div id=\'beacon_e076a91771\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8144&amp;campaignid=2973&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=e076a91771\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 17'] = '';
OA_output['spnsr ROS 17'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7965__zoneid=24__OXLCA=1__cb=e7bef15450__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_183.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7965__zoneid=24__OXLCA=1__cb=e7bef15450__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_e7bef15450\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7965&amp;campaignid=2919&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=e7bef15450\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 18'] = '';
OA_output['spnsr ROS 18'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8160__zoneid=24__OXLCA=1__cb=10e62c6294__oadest=https%3A%2F%2Fsnipcart.com%2F%3Futm_source%3Dsmashing-mag%26utm_medium%3Dbanner%26utm_campaign%3Dsmashing-mag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smashing_ad_snipcart.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Try our HTML/JS cart now!\' title=\'Try our HTML/JS cart now!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8160__zoneid=24__OXLCA=1__cb=10e62c6294__oadest=https%3A%2F%2Fsnipcart.com%2F%3Futm_source%3Dsmashing-mag%26utm_medium%3Dbanner%26utm_campaign%3Dsmashing-mag\' target=\'_blank\'>Try our HTML/JS cart now!<"+"/a><"+"div id=\'beacon_10e62c6294\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8160&amp;campaignid=2982&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=10e62c6294\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 19'] = '';
OA_output['spnsr ROS 19'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8196__zoneid=24__OXLCA=1__cb=99fa0ed05b__oadest=http%3A%2F%2Fwww.fonthaus.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=fonthaus_lust.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'FontHaus, Since 1990.\' title=\'FontHaus, Since 1990.\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8196__zoneid=24__OXLCA=1__cb=99fa0ed05b__oadest=http%3A%2F%2Fwww.fonthaus.com%2F\' target=\'_blank\'>FontHaus, Since 1990.<"+"/a><"+"div id=\'beacon_99fa0ed05b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8196&amp;campaignid=2999&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=99fa0ed05b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 20'] = '';
OA_output['spnsr ROS 20'] += "<"+"!-- Iframe tag: -->\n";
OA_output['spnsr ROS 20'] += "<"+"!-- begin ZEDO for channel:  Adobe 2_smashingmagazine , publisher: smashingmagazine.com , Ad Dimension: Smashing Magazine - 200 x 125 -->\n";
OA_output['spnsr ROS 20'] += "<"+"iframe src=\"http://c1.zedo.com/jsc/c1/ff2.html?n=1528;c=2463;s=437;d=46;w=200;h=125;l=[INSERT_CLICK_TRACKER_MACRO]\" frameborder=0 marginheight=0 marginwidth=0 scrolling=\"no\" allowTransparency=\"true\" width=200 height=125><"+"/iframe>\n";
OA_output['spnsr ROS 20'] += "<"+"!-- end ZEDO for channel:  Adobe 2_smashingmagazine , publisher: smashingmagazine.com , Ad Dimension: Smashing Magazine - 200 x 125 --><"+"br>\n";
OA_output['spnsr ROS 20'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8152__zoneid=24__OXLCA=1__cb=3334872e44__oadest=http%3A%2F%2Fxads.zedo.com%2Fads2%2Fc%3Fa%3D2008910%3Bx%3D11789%3Bg%3D41%3Bc%3D1528002463%2C1528002463%3Bi%3D4%3Bn%3D1528%3Bs%3D437%3B1%3D7%3B2%3D5%3Btg%3D1405612418%3Bvr%3D1%3Bm%3D4095%3Bw%3D3%3Bos%3D9%3Bct%3D1%3Bu%3DkhIPRTRPQLK21zUPA1vBvQ%2A%2A%7E092913%3Bz%3D0.13778241555669235%3Bainfo%3D%3Bcsv%3D0%3Bk%3D%255BINSERT_CLICK_TRACKER_MACRO%255Dhttp%3A%2F%2Fwww.adobe.com%2Fproducts%2Fcoldfusion-enterprise.html%3Fsdid%3DKOUSQ\" target=\"_blank\">Adobe ColdFusion 11<"+"/A><"+"div id=\'beacon_3334872e44\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8152&amp;campaignid=2977&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=3334872e44\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7938__zoneid=77__OXLCA=1__cb=921ab8f450__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Freports%2F2014-wcm-benchmarks%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dgleanster-report\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=410x125_b_2.png&contenttype=png\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_921ab8f450\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7938&amp;campaignid=2911&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=921ab8f450\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';
OA_output['Sponsor XXL 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7184__zoneid=77__OXLCA=1__cb=2f341eee74__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fsandbox%2Fdrag-and-drop-responsive-grid%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_grid_green_banner\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=lightcms-green-broad.png&contenttype=png\' width=\'410\' height=\'125\' alt=\'Drag &amp; Drop Responsive Grid\' title=\'Drag &amp; Drop Responsive Grid\' border=\'0\' /><"+"/a><"+"div id=\'beacon_2f341eee74\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7184&amp;campaignid=2687&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=2f341eee74\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 3'] = '';
OA_output['Sponsor XXL 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=8177__zoneid=77__OXLCA=1__cb=573d9a065c__oadest=http%3A%2F%2Fwww.1and1.com%2Fwordpress-blog-hosting%3Fac%3DOM.US.USk67K341446T7073\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ezgif.com-optimize.gif&contenttype=gif\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_573d9a065c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=8177&amp;campaignid=2993&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=573d9a065c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 4'] = '';
OA_output['Sponsor XXL 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7507__zoneid=77__OXLCA=1__cb=75dc7127d1__oadest=http%3A%2F%2Fsquarespace.com%2F%3Fchannel%3Ddisplay%26subchannel%3Dsmashing%26source%3Dus%26campaign%3Ddisplay_ad%26subcampaign%3Dtechnology\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=405x125_2.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_75dc7127d1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7507&amp;campaignid=2818&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=75dc7127d1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 5'] = '';
OA_output['Sponsor XXL 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7949__zoneid=77__OXLCA=1__cb=d5bb0ab716__oadest=https%3A%2F%2Fdeveloper.amazon.com%2Fappsandservices%2Fsolutions%2Fdevices%2Ffire-phone%2F%3Fsc_channel%3DBA%26sc_brand%3DFire_phone%26sc_campaign%3DFire_phone_Acq%26sc_place%3D410x125%26sc_country%3DUS%26sc_detail%3DBA_FirePhone%26sc_segment%3DGameDevelopers%26sc_publisher%3DSmashingMagazine%26sc_medium%3DBA_Fire_phone_Fire_phone_Acq_410x125_BA_FirePhone_GameDevelopers_SmashingMagazine_US\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner-410x125_fire_phone.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_d5bb0ab716\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7949&amp;campaignid=2913&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F&amp;cb=d5bb0ab716\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
